Repository Vero-Ventures/insurance-calculator, pull requests merged in 2024-05, with the labels that each got.

#16 Create api gateway
  dna-backend/.env
  dna-backend/.gitignore
  dna-backend/README.md
  dna-backend/eslint.config.mjs
  dna-backend/package-lock.json
  dna-backend/package.json
  dna-backend/packages/logger/package.json
  dna-backend/packages/logger/src/index.ts
  dna-backend/packages/logger/tsconfig.json
  dna-backend/services/gateway/package.json
  dna-backend/services/gateway/src/env.ts
  dna-backend/services/gateway/src/index.ts
  dna-backend/services/gateway/src/server/Gateway.ts
  dna-backend/services/gateway/src/zodSchemas.ts
  dna-backend/services/gateway/tsconfig.json
Labels: enhancement

#19 Hotfix: Redo eslint prettier configuration and dependencies (#18)
  dna-frontend/.eslintrc.json
  dna-frontend/.gitignore
  dna-frontend/.prettierignore
  dna-frontend/.prettierrc
  dna-frontend/.prettierrc.json
  dna-frontend/angular.json
  dna-frontend/eslint.config.mjs
  dna-frontend/package-lock.json
  dna-frontend/package.json
  dna-frontend/src/app/app.component.html
  dna-frontend/src/app/app.component.spec.ts
  dna-frontend/src/app/app.config.ts
  dna-frontend/src/app/core/components/example/example.component.spec.ts
  dna-frontend/src/app/core/components/example/example.component.ts
  dna-frontend/src/app/core/guards/auth.guard.spec.ts
  dna-frontend/src/app/core/guards/auth.guard.ts
  dna-frontend/src/app/core/services/example-service.service.ts
  dna-frontend/src/app/pages/calculator/calculator.component.spec.ts
  dna-frontend/src/app/pages/calculator/calculator.component.ts
  dna-frontend/src/app/shared/pipes/safe.pipe.ts
  dna-frontend/src/app/styles/theme/shadow.scss
  dna-frontend/src/main.ts
Labels: bug

#15 Setup Git Hooks and pre-commit hooks
  dna-backend/.eslintrc.json
  dna-backend/.husky/pre-commit
  dna-backend/.prettierrc.json
  dna-backend/package-lock.json
  dna-backend/package.json
  dna-frontend/.eslintrc.json
  dna-frontend/.husky/pre-commit
  dna-frontend/package-lock.json
  dna-frontend/package.json
  dna-frontend/requirements.txt
Labels: enhancement

#20 Implement Frontend User Authentication
  dna-frontend/.gitignore
  dna-frontend/package-lock.json
  dna-frontend/package.json
  dna-frontend/src/app/app.component.html
  dna-frontend/src/app/app.component.ts
  dna-frontend/src/app/app.routes.ts
  dna-frontend/src/app/core/components/auth/auth.component.html
  dna-frontend/src/app/core/components/auth/auth.component.scss
  dna-frontend/src/app/core/components/auth/auth.component.spec.ts
  dna-frontend/src/app/core/components/auth/auth.component.ts
  dna-frontend/src/app/core/components/example/example.component.html
  dna-frontend/src/app/core/components/example/example.component.ts
  dna-frontend/src/app/core/enums/example.ts
  dna-frontend/src/app/core/enums/supabase-status.ts
  dna-frontend/src/app/core/models/example.model.ts
  dna-frontend/src/app/core/models/profile.model.ts
  dna-frontend/src/app/core/services/example-service.service.spec.ts
  dna-frontend/src/app/core/services/example-service.service.ts
  dna-frontend/src/app/core/services/supabase.service.spec.ts
  dna-frontend/src/app/core/services/supabase.service.ts
  dna-frontend/src/app/pages/calculator/calculator.component.html
  dna-frontend/src/app/pages/calculator/calculator.component.ts
  dna-frontend/src/environments/environment.ts
  dna-frontend/tsconfig.json
Labels: enhancement

#26 Create core custom components for front end
  dna-frontend/.eslintrc.json
  dna-frontend/package-lock.json
  dna-frontend/package.json
  dna-frontend/src/app/app.routes.ts
  dna-frontend/src/app/core/components/action-item/action-item.component.html
  dna-frontend/src/app/core/components/action-item/action-item.component.scss
  dna-frontend/src/app/core/components/action-item/action-item.component.spec.ts
  dna-frontend/src/app/core/components/action-item/action-item.component.ts
  dna-frontend/src/app/core/components/bottom-bar/bottom-bar.component.html
  dna-frontend/src/app/core/components/bottom-bar/bottom-bar.component.scss
  dna-frontend/src/app/core/components/bottom-bar/bottom-bar.component.spec.ts
  dna-frontend/src/app/core/components/bottom-bar/bottom-bar.component.ts
  dna-frontend/src/app/core/components/horizontal-divider/horizontal-divider.component.html
  dna-frontend/src/app/core/components/horizontal-divider/horizontal-divider.component.scss
  dna-frontend/src/app/core/components/horizontal-divider/horizontal-divider.component.spec.ts
  dna-frontend/src/app/core/components/horizontal-divider/horizontal-divider.component.ts
  dna-frontend/src/app/core/components/landing-card/landing-card.component.html
  dna-frontend/src/app/core/components/landing-card/landing-card.component.scss
  dna-frontend/src/app/core/components/landing-card/landing-card.component.spec.ts
  dna-frontend/src/app/core/components/landing-card/landing-card.component.ts
  dna-frontend/src/app/core/components/line-chart/line-chart.component.html
  dna-frontend/src/app/core/components/line-chart/line-chart.component.scss
  dna-frontend/src/app/core/components/line-chart/line-chart.component.spec.ts
  dna-frontend/src/app/core/components/line-chart/line-chart.component.ts
  dna-frontend/src/app/core/components/multi-value-card/multi-value-card.component.html
  dna-frontend/src/app/core/components/multi-value-card/multi-value-card.component.scss
  dna-frontend/src/app/core/components/multi-value-card/multi-value-card.component.spec.ts
  dna-frontend/src/app/core/components/multi-value-card/multi-value-card.component.ts
  dna-frontend/src/app/core/components/subscription-card/subscription-card.component.html
  dna-frontend/src/app/core/components/subscription-card/subscription-card.component.scss
  dna-frontend/src/app/core/components/subscription-card/subscription-card.component.spec.ts
  dna-frontend/src/app/core/components/subscription-card/subscription-card.component.ts
  dna-frontend/src/app/core/components/value-card/value-card.component.html
  dna-frontend/src/app/core/components/value-card/value-card.component.scss
  dna-frontend/src/app/core/components/value-card/value-card.component.spec.ts
  dna-frontend/src/app/core/components/value-card/value-card.component.ts
  dna-frontend/src/app/core/components/value-list-card/value-list-card.component.html
  dna-frontend/src/app/core/components/value-list-card/value-list-card.component.scss
  dna-frontend/src/app/core/components/value-list-card/value-list-card.component.spec.ts
  dna-frontend/src/app/core/components/value-list-card/value-list-card.component.ts
  dna-frontend/src/app/core/components/vertical-divider/vertical-divider.component.html
  dna-frontend/src/app/core/components/vertical-divider/vertical-divider.component.scss
  dna-frontend/src/app/core/components/vertical-divider/vertical-divider.component.spec.ts
  dna-frontend/src/app/core/components/vertical-divider/vertical-divider.component.ts
  dna-frontend/src/app/core/models/value.model.ts
  dna-frontend/src/app/pages/test-page/test-page.component.html
  dna-frontend/src/app/pages/test-page/test-page.component.scss
  dna-frontend/src/app/pages/test-page/test-page.component.spec.ts
  dna-frontend/src/app/pages/test-page/test-page.component.ts
  dna-frontend/src/app/styles/theme/color.scss
  dna-frontend/src/app/styles/theme/type.scss
  dna-frontend/src/styles.scss
Labels: enhancement

#31 Remove placeholder button for sidebar toggle (#22)
  dna-frontend/src/app/core/components/sidebar/sidebar.component.html
Labels: bug

#39 Create appbar component
  dna-frontend/src/app/core/components/appbar/appbar.component.html
  dna-frontend/src/app/core/components/appbar/appbar.component.scss
  dna-frontend/src/app/core/components/appbar/appbar.component.spec.ts
  dna-frontend/src/app/core/components/appbar/appbar.component.ts
Labels: enhancement

#28 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#34 Fix existing ESLint errors and implement GitHub Actions
  .github/workflows/main.yml
  dna-backend/.eslintrc.json
  dna-backend/README.md
  dna-backend/eslint.config.mjs
  dna-backend/package.json
  dna-backend/packages/logger/tsconfig.json
  dna-backend/services/gateway/src/env.ts
  dna-backend/services/gateway/src/index.ts
  dna-backend/services/gateway/src/server/Gateway.ts
  dna-backend/services/gateway/src/zodSchemas.ts
  dna-backend/services/gateway/tsconfig.json
  dna-frontend/package.json
Labels: enhancement

#52 GitHub Actions secrets/token bug
  .github/workflows/main.yml
Labels: bug

#54 Create login pages
  dna-frontend/src/app/app.component.ts
  dna-frontend/src/app/app.routes.ts
  dna-frontend/src/app/core/components/action-item/action-item.component.html
  dna-frontend/src/app/core/components/action-item/action-item.component.scss
  dna-frontend/src/app/core/components/action-item/action-item.component.ts
  dna-frontend/src/app/core/components/auth/auth.component.html
  dna-frontend/src/app/core/components/landing-card/landing-card.component.html
  dna-frontend/src/app/core/components/landing-card/landing-card.component.scss
  dna-frontend/src/app/core/components/landing-card/landing-card.component.ts
  dna-frontend/src/app/pages/auth/auth.component.html
  dna-frontend/src/app/pages/auth/auth.component.scss
  dna-frontend/src/app/pages/auth/auth.component.spec.ts
  dna-frontend/src/app/pages/auth/auth.component.ts
  dna-frontend/src/app/pages/client-list/client-list.component.html
  dna-frontend/src/app/pages/client-list/client-list.component.scss
  dna-frontend/src/app/pages/client-list/client-list.component.spec.ts
  dna-frontend/src/app/pages/client-list/client-list.component.ts
  dna-frontend/src/app/pages/landing/landing.component.html
  dna-frontend/src/app/pages/landing/landing.component.scss
  dna-frontend/src/app/pages/landing/landing.component.spec.ts
  dna-frontend/src/app/pages/landing/landing.component.ts
  dna-frontend/src/app/pages/signup/signup.component.html
  dna-frontend/src/app/pages/signup/signup.component.scss
  dna-frontend/src/app/pages/signup/signup.component.spec.ts
  dna-frontend/src/app/pages/signup/signup.component.ts
  dna-frontend/src/styles.scss
Labels: enhancement

#55 Create an llm micro service with rag capabilities
  dna-advisor/.gitignore
  dna-advisor/api.py
  dna-advisor/lib/__init__.py
  dna-advisor/lib/model.py
  dna-advisor/lib/rag.py
  dna-advisor/main.py
  dna-advisor/requirements.txt
  dna-backend/README.md
  dna-backend/services/gateway/src/index.ts
  dna-backend/services/gateway/src/server/Gateway.ts
  dna-backend/services/gateway/src/zodSchemas.ts
Labels: enhancement

#69 Add bottom bar to all calculator pages
  dna-frontend/src/app/core/components/bottom-bar/bottom-bar.component.scss
  dna-frontend/src/app/pages/calculator/calculator.component.html
  dna-frontend/src/app/pages/calculator/calculator.component.scss
  dna-frontend/src/app/pages/calculator/calculator.component.ts
Labels: enhancement

#75 Create client component store with DB connection + fix and integrate auth guards
  dna-frontend/package-lock.json
  dna-frontend/package.json
  dna-frontend/src/app/app.config.ts
  dna-frontend/src/app/app.routes.ts
  dna-frontend/src/app/core/constants/canada-provinces.constant.ts
  dna-frontend/src/app/core/constants/tax.constant.ts
  dna-frontend/src/app/core/enums/ca-provinces.enum.ts
  dna-frontend/src/app/core/enums/supabase-status.enum.ts
  dna-frontend/src/app/core/guards/auth.guard.ts
  dna-frontend/src/app/core/models/client.model.ts
  dna-frontend/src/app/core/models/tax.model.ts
  dna-frontend/src/app/core/services/supabase.service.ts
  dna-frontend/src/app/pages/businesses/businesses.component.ts
  dna-frontend/src/app/pages/businesses/businesses.store.ts
  dna-frontend/src/app/pages/calculator/calculator.component.ts
  dna-frontend/src/app/pages/client/client.component.html
  dna-frontend/src/app/pages/client/client.component.ts
  dna-frontend/src/app/pages/client/client.store.ts
  dna-frontend/src/app/shared/pipes/age.pipe.ts
  dna-frontend/src/app/shared/pipes/non-negative.pipe.ts
  dna-frontend/src/app/shared/pipes/tax-bracket.pipe.ts
  dna-frontend/src/app/states/client.state.ts
  dna-frontend/src/environments/environment.ts
Labels: bug, enhancement

#74 Connect Advisor to Supabase vector store
  dna-advisor/README.md
  dna-advisor/lib/rag.py
  dna-advisor/main.py
  dna-advisor/requirements.txt
Labels: enhancement

#59 Add linting and formatting for Python
  .github/workflows/main.yml
  .pre-commit-config.yaml
  dna-advisor/api.py
  dna-advisor/lib/model.py
  dna-advisor/lib/rag.py
  dna-advisor/main.py
  dna-advisor/prerun.txt
  dna-advisor/requirements.txt
  dna-frontend/requirements.txt
Labels: enhancement

#93 Prune Advisor dependencies
  dna-advisor/requirements.txt
Labels: bug

#95 Implemented Client List Page Functionality
  dna-frontend/src/app/core/models/client-list.model.ts
  dna-frontend/src/app/core/services/supabase.service.ts
  dna-frontend/src/app/pages/client-list/client-list.component.html
  dna-frontend/src/app/pages/client-list/client-list.component.ts
  dna-frontend/src/app/pages/client-list/client-list.store.ts
  dna-frontend/src/app/states/client-list.state.ts
Labels: enhancement

#72 Create goals page UI
  dna-frontend/src/app/pages/goals/goals.component.html
  dna-frontend/src/app/pages/goals/goals.component.scss
  dna-frontend/src/app/pages/goals/goals.component.ts
Labels: enhancement

#94 Define default advisor host as url
  dna-backend/services/gateway/src/zodSchemas.ts
Labels: bug

#100 Dockerfiles & Docker Compose
  compose.yaml
  dna-advisor/.dockerignore
  dna-advisor/Dockerfile
  dna-backend/.dockerignore
  dna-backend/Dockerfile
  dna-frontend/.dockerignore
  dna-frontend/Dockerfile
Labels: enhancement

#121 Implement openai module
  dna-advisor/lib/model.py
  dna-advisor/main.py
  dna-advisor/requirements.txt
Labels: enhancement

#124 Downgrade advisor docker image to bullseye
  dna-advisor/Dockerfile
Labels: bug

#129 Finish implementing results pages
  dna-frontend/src/app/core/components/bar-chart/bar-chart.component.html
  dna-frontend/src/app/core/components/bar-chart/bar-chart.component.ts
  dna-frontend/src/app/core/components/chart-island/chart-island.component.html
  dna-frontend/src/app/core/components/chart-island/chart-island.component.scss
  dna-frontend/src/app/core/components/chart-island/chart-island.component.spec.ts
  dna-frontend/src/app/core/components/chart-island/chart-island.component.ts
  dna-frontend/src/app/core/components/legend/legend.component.html
  dna-frontend/src/app/core/components/legend/legend.component.scss
  dna-frontend/src/app/core/components/legend/legend.component.spec.ts
  dna-frontend/src/app/core/components/legend/legend.component.ts
  dna-frontend/src/app/core/components/line-chart/line-chart.component.html
  dna-frontend/src/app/core/components/line-chart/line-chart.component.scss
  dna-frontend/src/app/core/components/line-chart/line-chart.component.ts
  dna-frontend/src/app/core/components/multi-value-card/multi-value-card.component.scss
  dna-frontend/src/app/core/components/pie-chart/pie-chart.component.html
  dna-frontend/src/app/core/components/pie-chart/pie-chart.component.scss
  dna-frontend/src/app/core/components/pie-chart/pie-chart.component.ts
  dna-frontend/src/app/core/constants/graph.constant.ts
  dna-frontend/src/app/core/models/debt.model.ts
  dna-frontend/src/app/core/models/legend.model.ts
  dna-frontend/src/app/core/utils/charts.utils.ts
  dna-frontend/src/app/pages/asset-edit/asset-edit.component.ts
  dna-frontend/src/app/pages/assets/assets.component.html
  dna-frontend/src/app/pages/assets/assets.component.ts
  dna-frontend/src/app/pages/beneficiaries/beneficiaries.component.html
  dna-frontend/src/app/pages/beneficiaries/beneficiaries.component.ts
  dna-frontend/src/app/pages/businesses/businesses.component.html
  dna-frontend/src/app/pages/businesses/businesses.component.ts
  dna-frontend/src/app/pages/client/client.component.html
  dna-frontend/src/app/pages/client/client.component.ts
  dna-frontend/src/app/pages/debts/debts.component.html
  dna-frontend/src/app/pages/debts/debts.component.ts
  dna-frontend/src/app/pages/goals/goals.component.html
  dna-frontend/src/app/pages/goals/goals.component.scss
  dna-frontend/src/app/pages/goals/goals.component.ts
  dna-frontend/src/app/pages/test-page/test-page.component.html
  dna-frontend/src/app/pages/test-page/test-page.component.ts
  dna-frontend/src/app/shared/pipes/tax-bracket.pipe.ts
  dna-frontend/src/styles.scss
Labels: enhancement

#122 Feature/chat page UI
  dna-frontend/src/app/app.routes.ts
  dna-frontend/src/app/core/components/advisor-bar/advisor-bar.component.html
  dna-frontend/src/app/core/components/advisor-bar/advisor-bar.component.scss
  dna-frontend/src/app/core/components/advisor-bar/advisor-bar.component.spec.ts
  dna-frontend/src/app/core/components/advisor-bar/advisor-bar.component.ts
  dna-frontend/src/app/core/components/chat-input/chat-input.component.html
  dna-frontend/src/app/core/components/chat-input/chat-input.component.scss
  dna-frontend/src/app/core/components/chat-input/chat-input.component.spec.ts
  dna-frontend/src/app/core/components/chat-input/chat-input.component.ts
  dna-frontend/src/app/core/components/chatbox/chatbox.component.html
  dna-frontend/src/app/core/components/chatbox/chatbox.component.scss
  dna-frontend/src/app/core/components/chatbox/chatbox.component.spec.ts
  dna-frontend/src/app/core/components/chatbox/chatbox.component.ts
  dna-frontend/src/app/pages/advisor/advisor.component.html
  dna-frontend/src/app/pages/advisor/advisor.component.scss
  dna-frontend/src/app/pages/advisor/advisor.component.spec.ts
  dna-frontend/src/app/pages/advisor/advisor.component.ts
  dna-frontend/src/app/pages/landing/landing.component.html
Labels: enhancement

#132 Create and implement functionality for Total Needs page
  dna-frontend/src/app/core/models/total-needs.model.ts
  dna-frontend/src/app/core/services/supabase.service.ts
  dna-frontend/src/app/core/utils/totals.utils.ts
  dna-frontend/src/app/pages/assets/assets.component.ts
  dna-frontend/src/app/pages/businesses/businesses.component.html
  dna-frontend/src/app/pages/total-needs/total-needs.component.html
  dna-frontend/src/app/pages/total-needs/total-needs.component.ts
  dna-frontend/src/app/pages/total-needs/total-needs.store.ts
  dna-frontend/src/app/states/total-needs.state.ts
Labels: enhancement

#133 Implement profile import and export
  dna-frontend/src/app/core/components/appbar/appbar.component.html
  dna-frontend/src/app/core/components/appbar/appbar.component.ts
  dna-frontend/src/app/core/services/supabase.service.ts
  dna-frontend/src/app/pages/client-list/client-list.component.html
  dna-frontend/src/app/pages/client-list/client-list.component.ts
Labels: enhancement

#137 Change signup page message (#136)
  dna-frontend/src/app/pages/signup/signup.component.html
Labels: bug
